name: winget_gui
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluent_ui: ^4.8.6
  system_theme: ^2.3.1
  window_manager: ^0.3.8
  flutter_acrylic: ^1.1.3
  url_launcher: ^6.2.5
  expandable_text: ^2.3.0
  string_validator: ^1.0.2
  intl: ^0.18.1
  open_store: ^0.5.0
  favicon: ^1.1.2
  flutter_svg: ^2.0.10+1
  app_theme_mode: ^1.0.0
  shared_preferences: ^2.2.2
  ribs_json: ^1.0.0-dev.9
  ribs_core: ^1.0.0-dev.9
  http: ^1.2.1
  gallery_image_viewer: ^1.2.0
  yaml: ^3.1.2
  flutter_localized_locales: ^2.0.5
  collection: any
  pub_semver: ^2.1.4
  csv: ^6.0.0
  internet_connection_checker: ^1.0.0+1
  fluentui_system_icons: ^1.1.229
  provider: ^6.1.2
  dart_casing: ^3.0.1
  cron: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/