name: winget_gui
description: A new Flutter project.

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  fluent_ui: ^4.7.3
  system_theme: ^2.3.1
  window_manager: ^0.3.5
  flutter_acrylic: ^1.1.3
  url_launcher: ^6.1.12
  expandable_text: ^2.3.0
  string_validator: ^1.0.0
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  open_store: ^0.5.0
  expandable: ^5.0.1
  linkable: ^3.0.1
  go_router: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.2
  msix: ^3.16.1



flutter:
  generate: true


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
