name: winget_gui
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluent_ui: ^4.8.7
  system_theme: ^2.3.1
  window_manager: 0.3.8
  flutter_acrylic: ^1.1.3
  url_launcher: ^6.2.6
  expandable_text: ^2.3.0
  string_validator: ^1.0.2
  intl: any
  open_store: ^0.5.0
  favicon: ^1.1.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  shared_preferences_linux: 2.3.2
  ribs_json: ^1.0.0-dev.9
  ribs_core: ^1.0.0-dev.9
  http: ^1.2.1
  gallery_image_viewer: ^1.2.0
  yaml: ^3.1.2
  flutter_localized_locales: ^2.0.5
  collection: any
  internet_connection_checker: ^1.0.0+1
  fluentui_system_icons: ^1.1.236
  provider: ^6.1.2
  dart_casing: ^3.0.1
  cron: ^0.6.0
  sqflite: ^2.3.3
  path: ^1.9.0
  sqflite_common_ffi: any
  diacritic: ^0.1.5
  cached_network_image: ^3.3.1
  file_picker: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.2
  msix: ^3.16.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

msix_config:
  display_name: WingetGUI
  publisher_display_name: Wi42
  publisher: CN=Wi42, O=Wi42, C=Switzerland
  identity_name: wi42.winget-gui
  msix_version: 0.0.0.1
  capabilities: internetClient
  architecture: x64