name: winget_gui
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluent_ui: ^4.9.1
  system_theme: ^3.1.1
  window_manager: ^0.4.2
  flutter_acrylic: ^1.1.4
  url_launcher: ^6.3.0
  expandable_text: ^2.3.0
  string_validator: ^1.1.0
  intl: any
  open_store: ^0.5.0
  favicon: ^1.1.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  shared_preferences_linux: 2.3.2 # needed because with 2.4.0 it crashes because source file is not found
  ribs_json: ^1.0.0-dev.10
  ribs_core: ^1.0.0-dev.12
  http: ^1.2.2
  gallery_image_viewer: ^1.2.0
  yaml: ^3.1.2
  flutter_localized_locales: ^2.0.5
  collection: any
  internet_connection_checker: ^1.0.0+1
  fluentui_system_icons: ^1.1.257
  provider: ^6.1.2
  dart_casing: ^3.0.1
  cron: ^0.6.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi: any
  diacritic: ^0.1.6
  cached_network_image: ^3.4.1
  file_picker: ^8.1.2
  # ----- isar -----
  # Using the isar-community.dev because the official isar package is not updated
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  path_provider: ^2.1.4
  #path_provider_linux: 2.2.0
    # ----- \isar -----

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  build_runner: any
  dependency_validator: ^4.1.1
  flutter_lints: ^5.0.0
  msix: ^3.16.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

msix_config:
  display_name: WingetGUI
  publisher_display_name: Wi42
  publisher: CN=Wi42, O=Wi42, C=Switzerland
  identity_name: wi42.winget-gui
  msix_version: 0.0.0.1
  capabilities: internetClient
  architecture: x64