name: isar_persistent_storage
description: Persistent storage implementation for WingetGUI using Isar database
version: 0.0.1

publish_to: 'none'


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  persistent_storage_interface:
    path: ../interface
  winget_core:
    path: ../../winget_core
  json_file_loader:
    path: ../json_file_loader
  # Using the isar-community.dev because the official isar package is not updated
  isar_community:  3.3.0-dev.3
  isar_community_flutter_libs: 3.3.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_community_generator:  3.3.0-dev.3
  build_runner: ^2.4.15