name: isar_persistent_storage
description: Persistent storage implementation for WingetGUI using Isar database
version: 0.0.1

publish_to: 'none'


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  persistent_storage_interface:
    path: ../interface
  winget_core:
    path: ../../winget_core
  json_file_loader:
    path: ../json_file_loader
  # Using the isar-community.dev because the official isar package is not updated
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.1.8
  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  build_runner: ^2.4.15