; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "WingetGUI Dev"
#define MyAppVersion "1.0.0+1"
#define MyAppPublisher "Wi42"
#define MyAppExeName "winget_gui.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C563E47D-132E-4D61-B940-834E78CDD404}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\lukik\Documents\Code\Flutter\winget_gui\installers
OutputBaseFilename=mysetup_dev
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\flutter_acrylic_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\screen_retriever_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\system_theme_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\window_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\winget_gui.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lukik\Documents\Code\Flutter\winget_gui\build\windows\x64\runner\Debug\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

