name: winget_core
description: core components used in WingetGUI
version: 0.0.1


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: any
  intl: any
  ribs_json: ^1.0.0
  ribs_core: ^1.0.0
  json_annotation: ^4.12.0
  http: ^1.6.0
  string_validator: ^1.2.0
  diacritic: ^0.1.6


dev_dependencies:
  json_serializable: ^6.14.1
